### ISSUE TITLE
rails server error

### ISSUE THREAD

**Issue by foxlog** [railsbridge/docs#550]
create app with "rails new job_board -T", when type "rails server" appear error:

Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring sqlite3-1.3.11 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.11
/Users/Alex/.gems/gems/sqlite3-1.3.11/lib/sqlite3.rb:6:in `require': incompatible library version - /Users/Alex/.gems/gems/sqlite3-1.3.11/lib/sqlite3/sqlite3_native.bundle (fatal)
	from /Users/Alex/.gems/gems/sqlite3-1.3.11/lib/sqlite3.rb:6:in `rescue in <top (required)>'

try "gem pristine sqlite3 --version 1.3.11" and "gem pristine debug_inspector --version 0.0.2" not work.

I also found that if I just "rails new job_board"  will be ok.

**Comment by foxlog** [comment]
rails version not matched, fixed now.
